name: Jest Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest Tests
        run: npm run test:ci
